#
# Dev Profile
#
spring:
  application:
    name: student-api
  h2:
    console:
      enabled: true
      path: /h2Console
  datasource:
    url: jdbc:h2:mem:student-app
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  security:
    user:
      name: bhushan
      password: bhushan123


#H2 configuration

#loggin file
logging:
  file:
    name: DEV-app.log


